version: '3.9'

volumes:
  todo-api:

services:
  database:
    build:
      context: .
      target: todoapidb
    image: todoapidb
    container_name: todoapidb
    environment:
      MYSQL_DATABASE: todo_api
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - todo-api:/var/lib/mysql

  todoapi:
    build:
      context: .
      target: todoapi
    image: todoapi
    container_name: todoapi
    depends_on:
      - database
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - todo-api:/var/lib/go