version: '3.9'

volumes:
  todo-api:

services:
  todoapidb:
    container_name: todoapidb
    image: todoapidb
    build:
      context: .
      target: todoapidb
      args:
        - MYSQL_DATABASE=todo_api
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=appuser
        - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - todo-api:/var/lib/mysql

  todoapi:
    container_name: todoapi
    image: todoapi
    build:
      context: .
      target: todoapi
      args:
        - MYSQL_HOST=todoapidb
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - todo-api:/var/lib/go
    depends_on:
      - todoapidb