version: '3.9'

volumes:
  todo-api:

services:
  database:
    image: mysql:latest
    container_name: todoapi_db
    environment:
      MYSQL_DATABASE: todo_api
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - todo-api:/var/lib/mysql

  todoapi:
    build: .
    container_name: todo_api
    depends_on:
      - database
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - todo-api:/var/lib/go